### ISSUE TITLE
Modelling knowledge in mas_knowledge_base

### ISSUE THREAD

**Issue by argenos** [b-it-bots/mas_tutorials#6]
As we saw in GO, the ontology and the knowledge base are quite powerful. I see two parts, possibly two different tutorials:

* A tutorial on how to store or delete knowledge from the knowledge base, and how to make queries.
* A (smaller) tutorial on how to model things in the ontology, what conventions are we using, and possibly which tools

**Comment by alex-mitrevski** [comment]
I've assigned myself to this since I have to do it eventually, but I don't think that will happen any time soon unfortunately.
